imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  microbenchmarks:
    source:
      repository: https://github.com/martincostello/crank-sandbox
      branchOrCommit: main
      project: src/Microbenchmarks/Microbenchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true
  microbenchmarks-local:
    source:
      localFolder: .
      project: src/Microbenchmarks/Microbenchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true
  server:
    source:
      repository: https://github.com/martincostello/crank-sandbox
      branchOrCommit: main
      project: src/CrankSandbox/CrankSandbox.csproj
    readyStateText: Application started.
  local:
    source:
      localFolder: src/CrankSandbox
      project: CrankSandbox.csproj
    readyStateText: Application started.

scenarios:
  microbenchmarks:
    application:
      job: microbenchmarks
  microbenchmarks-local:
    application:
      job: microbenchmarks-local
  root:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /
  root-local:
    application:
      job: local
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
