imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    source:
      repository: https://github.com/martincostello/crank-sandbox
      branchOrCommit: main
      project: src/CrankSandbox/CrankSandbox.csproj
    readyStateText: Application started.
  local:
    source:
      localFolder: src/CrankSandbox
      project: CrankSandbox.csproj
    readyStateText: Application started.

scenarios:
  root:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /
  root-local:
    application:
      job: local
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
