name: perf-pr

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'
  workflow_dispatch:

jobs:
  perf-pr:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1

    - name: Install crank
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.Crank.Controller --version "0.2.0-*"
        dotnet tool install --global Microsoft.Crank.Agent --version "0.2.0-*"
        dotnet tool install --global Microsoft.Crank.PullRequestBot --version "0.2.0-*"

    - name: Run crank
      shell: pwsh
      run: |
        crank-pr --config ./crank-pr.yml --repository https://github.com/${{ github.repository }} --pull-request ${{ github.event.number }} --benchmarks root --profiles local --components sandbox
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
        DOTNET_ROLL_FORWARD: Major
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        NUGET_XMLDOC_MODE: skip
